package com.example.fznalarm.util

object Constants {
    const val ACTION_SET_EXACT_ALARM = "ACTION_SET_EXACT_ALARM"
    const val ACTION_SET_REPETITIVE_ALARM = "ACTION_SET_REPETITIVE_ALARM"
    const val ACTION_SET_FZN_ALARM1 = "ACTION_SET_FZN_ALARM1"
    const val ACTION_SET_FZN_ALARM2 = "ACTION_SET_FZN_ALARM2"
    const val ACTION_SET_FZN_ALARM3 = "ACTION_SET_FZN_ALARM3"
    const val ACTION_SET_FZN_ALARM4 = "ACTION_SET_FZN_ALARM4"
    const val ACTION_SET_FZN_ALARM5 = "ACTION_SET_FZN_ALARM5"


    const val EXTRA_EXACT_ALARM_TIME = "EXTRA_EXACT_ALARM_TIME"
}